### ISSUE TITLE
Cannot read property 'req' of undefined

### ISSUE THREAD

**Issue by skpnoes** [sidebase/nuxt-auth#111]
### Environment

3.0.0-rc.11

### Describe the bug

[nuxt] [request error] [unhandled] [500] Cannot read property 'req' of undefined
  at Module.getRequestURL (./node_modules/@sidebase/nuxt-auth/dist/runtime/utils/url.mjs:13:122)  
  at getSession (./node_modules/@sidebase/nuxt-auth/dist/runtime/composables/useSession.mjs:80:53)  
  at ./node_modules/@sidebase/nuxt-auth/dist/runtime/plugin.mjs:15:66  
  at Module.executeAsync (./node_modules/unctx/dist/index.mjs:92:19)  
  at ./node_modules/@sidebase/nuxt-auth/dist/runtime/plugin.mjs:15:49  
  at fn (./node_modules/nuxt/dist/app/nuxt.mjs:128:27)  
  at Object.callAsync (./node_modules/unctx/dist/index.mjs:49:19)  
  at callWithNuxt (./node_modules/nuxt/dist/app/nuxt.mjs:130:23)  
  at applyPlugin (./node_modules/nuxt/dist/app/nuxt.mjs:74:29)  
  at Module.applyPlugins (./node_modules/nuxt/dist/app/nuxt.mjs:84:11)

**Comment by BracketJohn** [comment]
Heya 👋 

I see that you're using RC.11 -> the auth-mpdule is on nuxt-stable since https://github.com/sidebase/nuxt-auth/releases/tag/0.2.0. In nuxt stable, the underlying `h3` was also changed so that `req` is only accessible via `event.node.req` (previously: `event.req`). So the problem here is likely the nuxt version -> can you upgrade to Nuxt stable and let us know if the problem persists?

**Comment by BracketJohn** [comment]
Likely resolved, closing this now due to inactivity. For everybody else: Use Nuxt 3 stable and you should be fine (:
