### ISSUE TITLE
Cannot read properties of undefined (reading '_')

### ISSUE THREAD

**Issue by marr** [sidebase/nuxt-auth#203]
### Environment

Nuxi 3.1.1                                                                                                                               14:13:52
                                                                                                                                         14:13:53
RootDir: /Users/david.marr/tmp/sidebase-tmp                                                                                              14:13:53
Nuxt project info: (copied to clipboard)                                                                                                 14:13:53

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.19.0`
- Nuxt Version:     `3.1.1`
- Nitro Version:    `2.1.1`
- Package Manager:  `npm@8.19.3`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@sidebase/nuxt-auth@0.4.0-alpha.5`
- Build Modules:    `-`
------------------------------

### Reproduction

[marr/nuxt3-sidebase-auth0](https://github.com/marr/nuxt3-sidebase-auth0)

1. `npm install`
2. `npm run dev`

### Describe the bug

Trying to setup the Auth0 provider with @sidebase/nuxt-auth is failing when loading middleware.

Complete error message:

> Cannot read properties of undefined (reading '_')
> 
> at parseActionAndProvider (./.nuxt/dev/index.mjs:412:33)
> at getInternalNextAuthRequestData (./.nuxt/dev/index.mjs:485:36)
> at Object.handler (./.nuxt/dev/index.mjs:502:31)
> at Object.handler (./node_modules/h3/dist/index.mjs:840:31)
> at processTicksAndRejections (node:internal/process/task_queues:96:5)
> at async toNodeHandle (./node_modules/h3/dist/index.mjs:915:7)
> at async Object.ufetch [as localFetch] (./node_modules/unenv/runtime/fetch/index.mjs:9:17)
> at async Object.errorhandler [as onError] (./.nuxt/dev/index.mjs:601:30)
> at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:922:9)

### Additional context

The error appears on the line in the generated _.nuxt/index.mjs_:

```
const parseActionAndProvider = ({ context }) => {
  const params = context.params._?.split("/"); // <-- here context.params is not defined.
```

<img width="612" alt="Screen Shot 2023-02-02 at 2 12 49 PM" src="https://user-images.githubusercontent.com/44376/216430309-61346913-974f-452e-947b-0c6b03e0ac2f.png">

### Logs

```shell
[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading '_')           14:14:30
  at parseActionAndProvider (./.nuxt/dev/index.mjs:412:33)  
  at getInternalNextAuthRequestData (./.nuxt/dev/index.mjs:485:36)  
  at Object.handler (./.nuxt/dev/index.mjs:502:31)  
  at Object.handler (./node_modules/h3/dist/index.mjs:840:31)  
  at processTicksAndRejections (node:internal/process/task_queues:96:5)  
  at async toNodeHandle (./node_modules/h3/dist/index.mjs:915:7)  
  at async Object.ufetch [as localFetch] (./node_modules/unenv/runtime/fetch/index.mjs:9:17)  
  at async Object.errorhandler [as onError] (./.nuxt/dev/index.mjs:601:30)  
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:922:9)
```
```

**Comment by marr** [comment]
Closing this. I mistakingly put the _[...].ts_ file in _server/middleware/auth_.
