### ISSUE TITLE
[nitro] [dev] [uncaughtException] TypeError: Auth0Provider is not a function

### ISSUE THREAD

**Issue by nengine** [sidebase/nuxt-auth#271]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.18.0`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `modules`, `auth`
- Runtime Modules:  `@sidebase/nuxt-auth@0.4.2`
- Build Modules:    `-`
------------------------------

### Describe the bug

Nuxt3 will not start for Auth0Provider.  GithubProver however seems to be working.

### Additional context

```
//~/server/api/auth/[...].ts
import { NuxtAuthHandler } from '#auth'
import Auth0Provider from "next-auth/providers/auth0";

export default NuxtAuthHandler({
    providers: [        
        Auth0Provider({
            clientId: process.env.AUTH0_CLIENT_ID,
            clientSecret: process.env.AUTH0_CLIENT_SECRET,
            issuer: process.env.AUTH0_ISSUER
        })
    ]
})

```

### Logs

```shell
[nitro] [dev] [uncaughtException] TypeError: Auth0Provider is not a function                                      06:44:51
    at file:///C:/Users/aungh/workspace/nodejs/nuxt3auth/.nuxt/dev/index.mjs:775:5
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:526:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)                                             06:44:44  
[nuxt] [request error] [unhandled] [500] Cannot access 'renderer$1' before initialization                         06:44:54
  at /C:/Users/aungh/workspace/nodejs/nuxt3auth/.nuxt/dev/index.mjs:642:65
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async Object.handler (/C:/Users/aungh/workspace/nodejs/nuxt3auth/node_modules/h3/dist/index.mjs:1196:19)
  at async Server.toNodeHandle (/C:/Users/aungh/workspace/nodejs/nuxt3auth/node_modules/h3/dist/index.mjs:1271:7)
[nuxt] [request error] [unhandled] [500] Cannot access 'renderer$1' before initialization                         06:44:54
  at /C:/Users/aungh/workspace/nodejs/nuxt3auth/.nuxt/dev/index.mjs:642:65
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async Object.handler (/C:/Users/aungh/workspace/nodejs/nuxt3auth/node_modules/h3/dist/index.mjs:1196:19)
  at async toNodeHandle (/C:/Users/aungh/workspace/nodejs/nuxt3auth/node_modules/h3/dist/index.mjs:1271:7)
  at async Object.ufetch [as localFetch] (/C:/Users/aungh/workspace/nodejs/nuxt3auth/node_modules/unenv/runtime/fetch/index.mjs:9:17)
  at async Object.errorhandler [as onError] (/C:/Users/aungh/workspace/nodejs/nuxt3auth/.nuxt/dev/index.mjs:616:30)
  at async Server.toNodeHandle (/C:/Users/aungh/workspace/nodejs/nuxt3auth/node_modules/h3/dist/index.mjs:1278:9)
```

**Comment by zoey-kaiser** [comment]
Hi @nengine 👋 

You have to call `.default()` on the Auth0Provider.

```ts
import { NuxtAuthHandler } from '#auth'
import Auth0Provider from "next-auth/providers/auth0";

export default NuxtAuthHandler({
    providers: [
        // Call .default() function here!        
        Auth0Provider.default({
            clientId: process.env.AUTH0_CLIENT_ID,
            clientSecret: process.env.AUTH0_CLIENT_SECRET,
            issuer: process.env.AUTH0_ISSUER
        })
    ]
})
```

this should fix this issue!

**Comment by nengine** [comment]
Thanks a lot.
