### ISSUE TITLE
Nuxt Auth cannot set token cookie after login in Netlify build

### ISSUE THREAD

**Issue by Nemure231** [sidebase/nuxt-auth#290]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.18.0`
- Nuxt Version:     `3.1.2`
- Nitro Version:    `2.1.2`
- Package Manager:  `npm@8.8.0`
- Builder:          `vite`
- User Config:      `css`, `modules`, `auth`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.1.0`, `@sidebase/nuxt-auth@0.4.3`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/Nemure231/auth-reproduction

https://auth-reproduction.netlify.app/

### Describe the bug

Hi, first thing i want to say, thanks for this module. However, i am kinda stuck deploying my website especially in Netlify.

After clone your https://github.com/sidebase/nuxt-auth-example/ nuxt-auth example, and then deploy in Netlify, i find that Nuxt Auth cannot set token in cookie.

In reproduction, i only tested with github login, i am not set the email login. Its probably hosting problem with Netlify, i also have netlify the log, i would really apreciate it if you begin to investigate this bug. Thank you.

No  "__Secure-next-auth.session-token" after login success
![Screenshot 2023-03-17 014215](https://user-images.githubusercontent.com/49015080/225721606-75396e89-b547-45c5-8014-ac8e4c90df3b.jpg)

### Logs

```shell
Mar 17, 01:41:00 AM: 108a597b ERROR  [next-auth][error][OAUTH_CALLBACK_ERROR] 
https://next-auth.js.org/errors#oauth_callback_error checks.state argument is missing {
  error: TypeError: checks.state argument is missing
      at Client.oauthCallback (/var/task/node_modules/openid-client/lib/client.js:520:13)
      at oAuthCallback (/var/task/node_modules/next-auth/core/lib/oauth/callback.js:129:29)
      at async Object.callback (/var/task/node_modules/next-auth/core/routes/callback.js:52:11)
      at async AuthHandler (/var/task/node_modules/next-auth/core/index.js:201:28)
      at async file:///var/task/chunks/nitro/netlify.mjs:421:24
      at async Object.handler (file:///var/task/chunks/nitro/config.mjs:767:19)
      at async toNodeHandle (file:///var/task/chunks/nitro/config.mjs:821:7)
      at async lambda (file:///var/task/chunks/nitro/netlify.mjs:613:13) {
    name: 'OAuthCallbackError',
    code: undefined
  },
  providerId: 'github',
  message: 'checks.state argument is missing'
}
```

**Comment by zoey-kaiser** [comment]
Hi @Nemure231 👋 

We are aware of the issues with Netlify deployments. Last week I began looking into multiple approaches onto how to properly deploy on Netlify. I had originally worked on figuring out Vercel deployments. If this is an option for you hosting with them could be a temporary solution until I figure out more information about the netlify deployments!

https://sidebase.io/nuxt-auth/recipes/vercel-deployment

**Comment by spaceninja** [comment]
Can confirm that switching from Netlify to Vercel fixed the problem. Looking forward to a fix, however, as I prefer Netlify.

**Comment by Nemure231** [comment]
Totally.

But hey, i was just wondering, can you make nuxt-auth make it more flexible?

Something like make option "storeCookie" when its true, nuxt-auth will set your cookie automaticly, but when its false just return the token value and make the user set it manually.

**Comment by andreasvirkus** [comment]
@spaceninja was your migration to Vercel painless? I've set up the project and my env variables but when visiting the site I get a `401`, with no further details in my logs 😕

**Comment by zoey-kaiser** [comment]
Hi @andreasvirkus 👋 

We also have an offical guide on vercel deployment. Have a look here: https://sidebase.io/nuxt-auth/recipes/vercel-deployment

Maybe it can help! Otherwise we would need to look into your code/vercel setup to see what is going wrong 🤗

**Comment by andreasvirkus** [comment]
Hi @zoey-kaiser, thanks! I followed the guide - would a new issue be more appropriate to investigate this?
