### ISSUE TITLE
Doesn't work on production

### ISSUE THREAD

**Issue by nikkorejz** [sidebase/nuxt-auth#421]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.3.2`
- Nitro Version:    `2.4.1`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `modules`, `auth`, `colorMode`, `app`, `runtimeConfig`
- Runtime Modules:  `nuxt-icon@0.4.0`, `nuxt-headlessui@1.1.4`, `@nuxtjs/color-mode@3.2.0`, `@nuxtjs/tailwindcss@6.6.4`, `@sidebase/nuxt-auth@0.6.0-beta.2`
- Build Modules:    `-`

### Describe the bug

In development build (`yarn dev`) authorization works
But `/api/token` throws error

`server/api/token.get.ts`:
```
import { getToken } from '#auth'

export default eventHandler(event => getToken({ event }))
```

Returns:
```
{
   "url":"/api/token",
   "statusCode":500,
   "statusMessage":"",
   "message":"Cannot read properties of undefined (reading 'computed')",
   "stack":"<pre><span class=\"stack\">at getServerOrigin (./.nuxt/dev/index.mjs:443:54)</span>\n<span class=\"stack\">at getToken (./.nuxt/dev/index.mjs:694:33)</span>\n<span class=\"stack\">at ./.nuxt/dev/index.mjs:1033:43</span>\n<span class=\"stack internal\">at ./node_modules/h3/dist/index.mjs:1191:47</span>\n<span class=\"stack internal\">at process.processTicksAndRejections (node:internal/process/task_queues:95:5)</span>\n<span class=\"stack internal\">at async Object.handler (./node_modules/h3/dist/index.mjs:1247:19)</span>\n<span class=\"stack internal\">at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:1322:7)</span></pre>"
}
```

In production build application fails right after startup

### Logs

```shell
istp-stagestable-web-1       | file:///nuxtapp/.output/server/chunks/nitro/node-server.mjs:413
istp-stagestable-web-1       |   const runtimeConfigOrigin = useRuntimeConfig().auth.computed.origin;
istp-stagestable-web-1       |                                                      ^
istp-stagestable-web-1       | 
istp-stagestable-web-1       | TypeError: Cannot read properties of undefined (reading 'computed')
istp-stagestable-web-1       |     at getServerOrigin (file:///nuxtapp/.output/server/chunks/nitro/node-server.mjs:413:54)
istp-stagestable-web-1       |     at file:///nuxtapp/.output/server/chunks/nitro/node-server.mjs:443:5
istp-stagestable-web-1       |     at createNitroApp (file:///nuxtapp/.output/server/chunks/nitro/node-server.mjs:1798:5)
istp-stagestable-web-1       |     at file:///nuxtapp/.output/server/chunks/nitro/node-server.mjs:1802:18
istp-stagestable-web-1       |     at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
istp-stagestable-web-1       | 
istp-stagestable-web-1       | Node.js v18.13.0
istp-stagestable-web-1 exited with code 1
```

**Comment by nikkorejz** [comment]
Ok, it solved:
`.env`
```
AUTH_ORIGIN=http://localhost:3000
```

`nuxt.config.ts`
```
auth: {
  origin: process.env.AUTH_ORIGIN,
  provider: {
    type: 'authjs'
  },
  globalAppMiddleware: {
    isEnabled: true
  }
},
```
But when I open site, I see 500 error - failed to fetch
```
istp-stagestable-web-1       | Listening http://[::]:3000
istp-stagestable-web-1       | [nuxt] [request error] [unhandled] [500] fetch failed (http://localhost:6060/api/auth/session?callbackUrl=http://localhost:6060/)
```
Could somebody help?

**Comment by mlutsiuk** [comment]
Must be related to #413

**Comment by nikkorejz** [comment]
Удалось решить:
1. Переключился на версию 0.5.0
2. Использовал nginx, который проксировал запросы в контейнер с nuxt-приложением
3. Использовал npm, вместо yarn. Yarn не ставил next-auth почему-то.
