### ISSUE TITLE
Azure login fails on localhost: ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by WolfVector** [sidebase/nuxt-auth#448]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.15.0
- Nuxt Version:     3.5.3
- Nitro Version:    2.4.1
- Package Manager:  npm@9.2.0
- Builder:          vite
- User Config:      devtools, modules, auth
- Runtime Modules:  @sidebase/nuxt-auth@0.5.0
- Build Modules:    -

### Describe the bug

I'm trying to do login using Azure, but for some reason  **localhost** is trying to use **https.** I didn't have this problem when using **next-auth** in Next.js or even Sveltekit.

![issue1](https://github.com/sidebase/nuxt-auth/assets/66027111/71847abb-e484-46a5-83c0-4f2e2d0b7678)

My `.env` file has:
```
# ... Azure Variables

AUTH_URL=http://localhost:3000
AUTH_TRUST_HOST=http://localhost:3000
AUTH_ORIGIN=http://localhost:3000
```

**nuxt.config.ts**
```js
export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: ['@sidebase/nuxt-auth'],
  auth: {
    // The module is enabled. Change this to disable the module
    isEnabled: true,
    // The origin is set to the development origin. Change this when deploying to production by setting `origin` in this config before build-time or by exporting `AUTH_ORIGIN` by running `export AUTH_ORIGIN=...`
    origin: 'http://localhost:3000',
    // The base path to the authentication endpoints. Change this if you want to add your auth-endpoints at a non-default location
    basePath: '/api/auth',
    // Whether to periodically refresh the session. Change this to `true` for a refresh every seconds or set this to a number like `5000` for a refresh every 5000 milliseconds (aka: 5 seconds)
    enableSessionRefreshPeriodically: false,
    // Whether to refresh the session whenever a window focus event happens, i.e, when your user refocuses the window. Set this to `false` to turn this off
    enableSessionRefreshOnWindowFocus: true,
    // Whether to add a global authentication middleware that will protect all pages without exclusion
    globalAppMiddleware: false,
    // Select the default-provider to use when `signIn` is called. Setting this here will also effect the global middleware behavior: E.g., when you set it to `github` and the user is unauthorized, they will be directly forwarded to the Github OAuth page instead of seeing the app-login page
    defaultProvider: undefined,
    // Whether to automatically set the callback url to the page the user tried to visit when the middleware stopped them. This is useful to disable this when using the credentials provider, as it does not allow a `callbackUrl`. Setting this to a string-value will result in that being used as the callbackUrl path.
    addDefaultCallbackUrl: true,
    // Configuration of the global auth-middleware (only applies if you set `globalAppMiddleware: true` above!)
    globalMiddlewareOptions: {
        // Whether to allow access to 404 pages without authentication. Set this to `false` to force users to sign-in before seeing `404` pages. Setting this to false may lead to vue-router problems (as the target page does not exist)
        allow404WithoutAuth: true,
        // Whether to automatically set the callback url to the page the user tried to visit when the middleware stopped them. This is useful to disable this when using the credentials provider, as it does not allow a `callbackUrl`. Setting this to a string-value will result in that being used as the callbackUrl path. Note: You also need to set the global `addDefaultCallbackUrl` setting to `false` if you want to fully disable this for the global middleware.
        addDefaultCallbackUrl: true
    }
  }
})
```

### Logs

```shell
[13:53:34] [nuxt] [request error] [unhandled] [500] Invalid URL
  at new NodeError (node:internal/errors:399:5)
  at URL.onParseError (node:internal/url:566:9)
  at new URL (node:internal/url:646:5)
  at Object.redirect (D:\Documentos\nuxt\upload-manager\node_modules\next-auth\core\lib\default-callbacks.js:16:65)
  at createCallbackUrl (D:\Documentos\nuxt\upload-manager\node_modules\next-auth\core\lib\callback-url.js:20:35)
  at init (D:\Documentos\nuxt\upload-manager\node_modules\next-auth\core\init.js:131:48)
```

**Comment by andreasvirkus** [comment]
Try changing `auth.origin` to `auth.baseURL` (https://github.com/sidebase/nuxt-auth/issues/374#issuecomment-1559411256) in your Nuxt config

**Comment by zoey-kaiser** [comment]
@WolfVector, has the recommendation from @andreasvirkus helped? I will close this issue for now, if the issue still persists feel free to reply and we can reopen this issue!
