### ISSUE TITLE
GetSessionAndUserError with Nuxt-auth using typeorm and synchronize: false

### ISSUE THREAD

**Issue by SamG92** [sidebase/nuxt-auth#462]
### Environment

- Operating System: Darwin
- Node Version:     v18.16.0
- Nuxt Version:     3.6.1
- Nitro Version:    2.5.1
- Package Manager:  npm@9.5.1
- Builder:          vite
- User Config:      vite, css, app, auth, modules, runtimeConfig
- Runtime Modules:  nuxt-icon@0.1.8, @sidebase/nuxt-auth@0.5.0, nuxt-mail@4.0.1
- Build Modules:    -

### Describe the bug

Hello,

I'm using Nuxt-Auth last stable version with TypeORMLegacyAdapter and my relational database.

Everything is working fine with "synchronize: true" in my adapter settings.

But whenever I put "synchronize: false" instead of "synchronize: true", I'm getting a "GetSessionAndUserError" and "https://next-auth.js.org/errors#session_error metadata.findEmbeddedWithPropertyPath is not a function TypeError: metadata.findEmbeddedWithPropertyPath is not a function".

I does not seem to come from my database: I switched from mysql to postgres and it is not working either.

Any idea why I get this annoying error preventing me to deploy to production?

Thanks a lot for your help!
Samuel

### Logs

```shell
[next-auth][error][SESSION_ERROR]                                                                            12:08:13
https://next-auth.js.org/errors#session_error metadata.findEmbeddedWithPropertyPath is not a function TypeError: metadata.findEmbeddedWithPropertyPath is not a function
    at /Users/***/Sites/vuejs/***/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2112:36
    at Array.forEach (<anonymous>)
    at SelectQueryBuilder.buildRelations (/Users/Samuel/Sites/vuejs/immocarto/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2107:32)
    at SelectQueryBuilder.applyFindOptions (/Users/Samuel/Sites/vuejs/immocarto/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1626:22)
    at SelectQueryBuilder.setFindOptions (/Users/Samuel/Sites/vuejs/immocarto/node_modules/typeorm/query-builder/SelectQueryBuilder.js:69:14)
    at EntityManager.findOne (/Users/***/Sites/vuejs/***/node_modules/typeorm/entity-manager/EntityManager.js:543:14)
    at getSessionAndUser (/Users/***/Sites/vuejs/***/node_modules/@next-auth/typeorm-legacy-adapter/dist/index.js:348:44)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  name: 'GetSessionAndUserError',
  code: undefined
}
```

**Comment by zoey-kaiser** [comment]
Hi @SamG92,

I sadly cannot help you much with this issue, as it fully results from NextAuth. If you are still planing on continuing the investigation, please reach out to the NextAuth team and see if they can support you. I am sorry that I cannot be much of help here.
