### ISSUE TITLE
Trouble when deploying to Netlify

### ISSUE THREAD

**Issue by trampolinstudio** [sidebase/nuxt-auth#492]
### Environment

Netlify Environment

Node v18.17.0
Nuxi 3.6.5
vite 4.3.9

Tried a couple configs, from https://sidebase.io/nuxt-auth/configuration/nuxt-config to simpler variants.

### Describe the bug

We deploy the module locally with success but when deploying on Netlify, we get a lot of the following errors (for many subpages). We assume that the "localhost" could be the problem in callbackUrl but not sure. We are also unable to change it, did we miss something here? 

Thank you!

### Logs

```shell
11:29:15 PM: [info] [nitro] Prerendering 26 routes
**11:29:17 PM: [error] [nuxt] [request error] [unhandled] [502]  (502 Bad Gateway (****/api/auth/session?callbackUrl=http://localhost/features))**
11:29:17 PM:   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
11:29:17 PM:   at async $fetchRaw2 (./node_modules/ofetch/dist/shared/ofetch.d438bb6f.mjs:234:14)
11:29:17 PM:   at async $fetch2 (./node_modules/ofetch/dist/shared/ofetch.d438bb6f.mjs:239:15)
11:29:17 PM:   at async ./.nuxt/prerender/chunks/app/server.mjs:1958:62
11:29:17 PM:   at async Object.callAsync (./node_modules/unctx/dist/index.mjs:72:16)
11:29:17 PM:   at async applyPlugin (./.nuxt/prerender/chunks/app/server.mjs:137:35)
11:29:17 PM:   at async applyPlugins (./.nuxt/prerender/chunks/app/server.mjs:153:7)
11:29:17 PM:   at async createNuxtAppServer (./.nuxt/prerender/chunks/app/server.mjs:6684:7)
11:29:17 PM:   at async Object.renderToString (./node_modules/vue-bundle-renderer/dist/runtime.mjs:176:19
```

**Comment by fabiovaz** [comment]
ssr: false?

**Comment by zoey-kaiser** [comment]
Hi @trampolinstudio,

Netlify should work as I know of multiple people using it to deploy their NuxtAuth apps! I assume there is some issue in your project where the `BaseURL` environment variable is being overridden. Can you check to see:

- Where you have your environment variables set
- If there are any environment variables Netlify may overwrite?

**Comment by zoey-kaiser** [comment]
Hi everyone!

I am closing this issue due to inactivity. Please open a new issue if this issue still occurs or you would like to continue the discussion.
