### ISSUE TITLE
Build fails with prerender step - 500 Internal Server error

### ISSUE THREAD

**Issue by andreasvirkus** [sidebase/nuxt-auth#533]
### Environment

```
"@sidebase/nuxt-auth": "0.5.0"
"next-auth": "4.21.1"


------------------------------
- Operating System: Darwin
- Node Version:     v19.4.0
- Nuxt Version:     3.7.3
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      modules, css, experimental, auth, runtimeConfig, devServer, nitro
- Runtime Modules:  @nuxtjs/tailwindcss@^6.8.0, @nuxtjs/html-validator@^1.5.2, @sidebase/nuxt-auth@0.5.0
- Build Modules:    -
------------------------------
```

### Describe the bug

Running `nuxt build` results in the actual bundling being successful, but the prerender step fails with these errors:

```
[2:57:56 PM] ℹ .nuxt/dist/server/server.mjs                            64.34 kB │ map: 131.48 kB
ℹ ✓ built in 889ms                                                          2:57:56 PM
✔ Server built in 895ms                                                     2:57:56 PM
✔ Generated public .output/public                                     nitro 2:57:56 PM
ℹ Initializing prerenderer     

[2:57:57 PM]  WARN  Export "getServerSession" of module "../../node_modules/@sidebase/nuxt-auth/dist/runtime/server/services/nuxtAuthHandler.mjs" was reexported through module "../../node_modules/@sidebase/nuxt-auth/dist/runtime/server/services/index.mjs" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "server/api/slack/users.ts" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.

ℹ Prerendering 1 routes                                               nitro 2:57:57 PM

[2:57:58 PM]  ERROR  [nuxt] [request error] [unhandled] [500] [GET] "https://matchbox-staging.vercel.app/api/auth/session?callbackUrl=http://localhost/": 500 Internal Server Error
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async $fetchRaw2 (/Users/anc/code/matchbox/monorepo/node_modules/ofetch/dist/shared/ofetch.00501375.mjs:256:14)
  at async $fetch2 (/Users/anc/code/matchbox/monorepo/node_modules/ofetch/dist/shared/ofetch.00501375.mjs:261:15)
  at async ./.nuxt/prerender/chunks/app/server.mjs:1260:62
  at async Object.callAsync (/Users/anc/code/matchbox/monorepo/node_modules/nuxi/dist/shared/nuxi.bf5ca6d6.mjs:97:16)
  at async applyPlugin (./.nuxt/prerender/chunks/app/server.mjs:128:35)
  at async applyPlugins (./.nuxt/prerender/chunks/app/server.mjs:148:7)
  at async createNuxtAppServer (./.nuxt/prerender/chunks/app/server.mjs:1868:7)
  at async Object.renderToString (/Users/anc/code/matchbox/monorepo/node_modules/vue-bundle-renderer/dist/runtime.mjs:173:19)
  at async ./.nuxt/prerender/chunks/renderer.mjs:455:21


 ERROR  HTML validation errors found for /                                   2:57:59 PM

inline
  2:2  error  <html> is missing required "lang" attribute  element-required-attributes
  3:2  error  <head> element must have <title> as content  element-required-content

✖ 2 problems (2 errors, 0 warnings)

More information:
  https://html-validate.org/rules/element-required-attributes.html
  https://html-validate.org/rules/element-required-content.html



  ├─ / (1663ms)                                                        nitro 2:57:59 PM
  │ └── Error: [500] Internal Server Error
                                                                       nitro 2:57:59 PM
Errors prerendering:
  ├─ / (1663ms)                                                        nitro 2:57:59 PM
  │ └── Error: [500] Internal Server Error
                                                                       nitro 2:57:59 PM

 ERROR  Exiting due to prerender errors.                                     2:57:59 PM

  at prerender (/Users/anc/code/matchbox/monorepo/node_modules/nitropack/dist/shared/nitro.d72ac66e.mjs:212:11)
  at async /Users/anc/code/matchbox/monorepo/node_modules/nuxt/dist/index.mjs:2864:7
  at async build (/Users/anc/code/matchbox/monorepo/node_modules/nuxt/dist/index.mjs:4218:5)
  at async Object.run (/Users/anc/code/matchbox/monorepo/node_modules/nuxi/dist/chunks/build.mjs:92:5)
  at async runCommand$1 (/Users/anc/code/matchbox/monorepo/node_modules/nuxi/dist/shared/nuxi.9d864d83.mjs:1647:7)
  at async runCommand$1 (/Users/anc/code/matchbox/monorepo/node_modules/nuxi/dist/shared/nuxi.9d864d83.mjs:1638:11)
  at async runMain$1 (/Users/anc/code/matchbox/monorepo/node_modules/nuxi/dist/shared/nuxi.9d864d83.mjs:1770:7)



 ERROR  Exiting due to prerender errors.                                     2:57:59 PM

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Additional context

The local/dev server works just fine.

**Comment by andreasvirkus** [comment]
Migrated to `0.6.0-beta.5` and changed `auth.origin` setting to `auth.baseURL` and no longer having this issue.
