### ISSUE TITLE
500 error calling getSession endpoint even if getSession is set to false 

### ISSUE THREAD

**Issue by cccaballero** [sidebase/nuxt-auth#774]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.9.0
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  npm@10.1.0
- Builder:          -
- User Config:      devtools, runtimeConfig, modules, auth
- Runtime Modules:  @sidebase/nuxt-auth@0.7.2
- Build Modules:    -
------------------------------

### Reproduction

I set the following config:

```
auth: {
    baseURL: 'http://localhost:8000'
    provider: {
      type: 'refresh',
      endpoints: {
        signIn: { path: `/auth/login/`, method: 'post' },
        signOut: { path: `/auth/logout/`, method: 'post' },
        signUp: { path: `/auth/registration/`, method: 'post' },
        getSession: false
      },
      token: { signInResponseTokenPointer: `/auth/token/verify/` },
      refreshToken: { signInResponseRefreshTokenPointer: `/auth/token/refresh/` },
    }
  }
```

My backend is running in a different server (Django app) exposed in port 8000 and my frontend nuxt apllication is exposed in port 3000

### Describe the bug

When the nuxt app loads, I get the following error:

```
404
[GET] "http://localhost:8000/api/auth/session?callbackUrl=http:%2F%2Flocalhost:3001%2F": 404 Not Found
```

### Additional context

It looks like nuxt-auth is trying to call a session endpoint even though I'm setting `getSession` to `false`.

### Logs

```shell-script
client.mjs:30 
        
        
       GET http://localhost:8000/api/auth/session?callbackUrl=http:%2F%2Flocalhost:3001%2F 404 (Not Found)
$fetchRaw2 @ ofetch.37386b05.mjs?v=8708b347:222
await in $fetchRaw2 (async)
$fetch2 @ ofetch.37386b05.mjs?v=8708b347:268
_fetch @ fetch.mjs?v=8708b347:6
await in _fetch (async)
getSession @ useAuth.mjs?v=8708b347:108
await in getSession (async)
(anonymous) @ plugin.mjs?v=8708b347:17
executeAsync @ index.mjs?v=8708b347:111
(anonymous) @ plugin.mjs?v=8708b347:17
(anonymous) @ client.mjs:30
executeAsync @ index.mjs?v=8708b347:111
setup @ client.mjs:30
(anonymous) @ nuxt.js?v=8708b347:137
fn @ nuxt.js?v=8708b347:214
runWithContext @ runtime-core.esm-bundler.js?v=8708b347:3089
callWithNuxt @ nuxt.js?v=8708b347:220
(anonymous) @ nuxt.js?v=8708b347:37
run @ reactivity.esm-bundler.js?v=8708b347:32
runWithContext @ nuxt.js?v=8708b347:37
applyPlugin @ nuxt.js?v=8708b347:137
executePlugin @ nuxt.js?v=8708b347:156
applyPlugins @ nuxt.js?v=8708b347:187
await in applyPlugins (async)
initApp @ entry.js:48
(anonymous) @ entry.js:66
Show 20 more frames
Show lessUnderstand this error
nuxt.js?v=8708b347:122 [nuxt] error caught during app initialization FetchError: [GET] "http://localhost:8000/api/auth/session?callbackUrl=http:%2F%2Flocalhost:3001%2F": 404 Not Found
    at async $fetch2 (ofetch.37386b05.mjs?v=8708b347:268:15)
    at async plugin.mjs?v=8708b347:17:61
    at async setup (client.mjs:30:36)
    at async applyPlugin (nuxt.js?v=8708b347:137:25)
    at async executePlugin (nuxt.js?v=8708b347:173:9)
    at async applyPlugins (nuxt.js?v=8708b347:187:5)
    at async initApp (entry.js:48:7)
```
```

**Comment by cccaballero** [comment]
I'm currently testing in version `0.8.0-alpha.2`. When I call the `signIn` function with `redirect: false` included in the `signInOptions` parameter, I don't encounter the on-screen 404 error anymore. However, the module still calls `getSession` and the token data obtained during `signIn` is cleared. Maybe this is because:

https://github.com/sidebase/nuxt-auth/blob/faa039b72da2c64d9c214f0502dea053c7a4ff84/src/runtime/composables/local/useAuth.ts#L81

This condition is not met because `getSessionOptions` is undefined but the token exists. As a result, the function execution continues but fails when trying to call the getSession endpoint, and the token value is cleared.

I don't need `getSession` at all, because my API is stateless and there is no session in the server side.

**Comment by zoey-kaiser** [comment]
Hi @cccaballero 👋 

Thanks for the detailed outline of the issue and investigation! Would you be willing to open a PR to patch this? We can then look to include this inside the 0.8.0 release!

**Comment by bitfactory-frank-spee** [comment]
This could be closed and/or resolved through using the `callGetSession: false` option for the `signIn` method. Although I am not sure if this works for refresh, but there are several related issues open about that.

**Comment by phoenix-ru** [comment]
I don't know if it's possible to use the module with `getSession` being set to `false`, as this endpoint is responsible for the authenticated status of the module. If you fully disable it, your Nuxt app will not have a way of knowing if a user is authenticated or not (having cookies != being authenticated, as their validity needs to be somehow verified).

At the moment NuxtAuth doesn't support session-less flows, but I can envision adding an `unknown` authenticated status for usecases like @cccaballero mentioned, where you call `signIn` and never re-check the authentication status. However, I don't know if this is such a common thing to do.
