### ISSUE TITLE
When `useAuth` is called in middleware, Nuxt throws a 500 error

### ISSUE THREAD

**Issue by TheDutchCoder** [sidebase/nuxt-auth#794]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.7.0
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  npm@10.1.0
- Builder:          -
- User Config:      app, auth, components, css, devServer, devtools, eslint, modules, router, runtimeConfig, sourcemap, srcDir, experimental, vite
- Runtime Modules:  @nuxt/eslint@0.3.13, @nuxtjs/i18n@8.3.1, nuxt-jsonld@2.0.8, @nuxtjs/device@3.1.1, @nuxtjs/robots@3.0.0, @vueuse/nuxt@10.11.0, @sidebase/nuxt-auth@0.8.0
- Build Modules:    -
------------------------------

### Reproduction

Your reproduction links don't include nuxt-auth, you should fix that first

### Describe the bug

When defining middleware (wether in a separate file or inline), the nuxt sidebase module throws Nuxt internal errors:
```
at useNuxtApp (./node_modules/nuxt/dist/app/nuxt.js:249:13)
at Module.useRuntimeConfig (./node_modules/nuxt/dist/app/nuxt.js:259:10)
at Module.formatToken (./node_modules/@sidebase/nuxt-auth/dist/runtime/utils/local.mjs:6:84)
at ./node_modules/@sidebase/nuxt-auth/dist/runtime/composables/local/useAuthState.mjs:31:76
at ReactiveEffect.fn (./node_modules/@vue/reactivity/dist/reactivity.cjs.js:994:13)
at ReactiveEffect.run (./node_modules/@vue/reactivity/dist/reactivity.cjs.js:181:19)
at get value (./node_modules/@vue/reactivity/dist/reactivity.cjs.js:1006:109)
at Reflect.get ()
at ReadonlyReactiveHandler.get (./node_modules/@vue/reactivity/dist/reactivity.cjs.js:482:25)
at Object.onRequest (./src/plugins/ofetch.ts:58:39)
```

**Comment by TheDutchCoder** [comment]
I can't repro this on a clean install, so I'm assuming the errors actually originates somewhere else.
