### ISSUE TITLE
'Invalid URL' on v 0.10.0

### ISSUE THREAD

**Issue by agracia-foticos** [sidebase/nuxt-auth#970]
### Environment

- Operating System: `Linux`
- Node Version:     `v22.8.0`
- Nuxt Version:     `3.14.1592`
- CLI Version:      `3.17.1`
- Nitro Version:    `2.10.4`
- Package Manager:  `yarn@4.3.1`
- Builder:          `-`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

i have this config:

```
 auth: {        
     // @ts-ignore (isEnabled boolean type)
     //BE CAREFULL, With visual studio debugger isEnabled can't be false, fails... issue opened
     isEnabled                         : true, //all environment variables are strings
     baseURL                           : `${process.env.NUXT_BASE_URL}/api/auth`, // The origin is set to the development origin. Change this when deploying to production by setting `origin` in this config before build-time or by exporting `AUTH_ORIGIN` by running `export AUTH_ORIGIN=...`                  
     // Whether to add a global authentication middleware that will protect all pages without exclusion
     globalAppMiddleware : true,
     provider                          : { type: 'authjs' },
     sessionRefresh : {
        enablePeriodically              : 86400000, //refresh the session every day
        enableOnWindowFocus             : true
     }
 },
```

1. go to localhost:3000
2. Server responses with error 500 and 
```
error {
  url: '/',
  statusCode: 500,
  statusMessage: '',
  message: 'Invalid URL',
  stack: '<pre><span class="stack internal">at new URL (node:internal/url:816:29)</span>\n' +
    '<span class="stack internal">at /home/web/var/www/site/node_modules/@sidebase/nuxt-auth/dist/runtime/composables/authjs/utils/navigateToAuthPage.js:15:31</span>\n' +
    '<span class="stack internal">at runNextTicks (node:internal/process/task_queues:65:5)</span>\n' +
    '<span class="stack internal">at process.processImmediate (node:internal/timers:459:9)</span>\n' +
    '<span class="stack internal">at process.callbackTrampoline (node:internal/async_hooks:130:17)</span>\n' +
    '<span class="stack internal">at async Object.callAsync (/home/web/var/www/site/node_modules/unctx/dist/index.mjs:72:16)</span>\n' +
    '<span class="stack internal">at async Object.callAsync (/home/web/var/www/site/node_modules/unctx/dist/index.mjs:72:16)</span>\n' +
    '<span class="stack internal">at async /home/web/var/www/site/node_modules/nuxt/dist/pages/runtime/plugins/router.js:180:26</span></pre>'
}
3. Automatic, (without any action), redirects to http://localhost:3000/login?callbackUrl=http://localhost:3000/


If i turn globalAppMiddleware to false, works OK
```

### Describe the bug

i have this config:

```
 auth: {        
     // @ts-ignore (isEnabled boolean type)
     //BE CAREFULL, With visual studio debugger isEnabled can't be false, fails... issue opened
     isEnabled                         : true, //all environment variables are strings
     baseURL                           : `${process.env.NUXT_BASE_URL}/api/auth`, // The origin is set to the development origin. Change this when deploying to production by setting `origin` in this config before build-time or by exporting `AUTH_ORIGIN` by running `export AUTH_ORIGIN=...`                  
     // Whether to add a global authentication middleware that will protect all pages without exclusion
     globalAppMiddleware : true,
     provider                          : { type: 'authjs' },
     sessionRefresh : {
        enablePeriodically              : 86400000, //refresh the session every day
        enableOnWindowFocus             : true
     }
 },
```

1. go to localhost:3000
2. Server responses with error 500 and 
```
error {
  url: '/',
  statusCode: 500,
  statusMessage: '',
  message: 'Invalid URL',
  stack: '<pre><span class="stack internal">at new URL (node:internal/url:816:29)</span>\n' +
    '<span class="stack internal">at /home/web/var/www/site/node_modules/@sidebase/nuxt-auth/dist/runtime/composables/authjs/utils/navigateToAuthPage.js:15:31</span>\n' +
    '<span class="stack internal">at runNextTicks (node:internal/process/task_queues:65:5)</span>\n' +
    '<span class="stack internal">at process.processImmediate (node:internal/timers:459:9)</span>\n' +
    '<span class="stack internal">at process.callbackTrampoline (node:internal/async_hooks:130:17)</span>\n' +
    '<span class="stack internal">at async Object.callAsync (/home/web/var/www/site/node_modules/unctx/dist/index.mjs:72:16)</span>\n' +
    '<span class="stack internal">at async Object.callAsync (/home/web/var/www/site/node_modules/unctx/dist/index.mjs:72:16)</span>\n' +
    '<span class="stack internal">at async /home/web/var/www/site/node_modules/nuxt/dist/pages/runtime/plugins/router.js:180:26</span></pre>'
}
3. Automatic, (without any action), redirects to http://localhost:3000/login?callbackUrl=http://localhost:3000/


If i turn globalAppMiddleware to false, works OK
```

**Comment by phoenix-ru** [comment]
Hi @agracia-foticos , thanks a lot for your report about v0.10! This data is valuable as there were lots of breaking changes and internal refactoring.
As our company is on a vacation, we could only get back to Sidebase work in the first/second week of January 2025.
Sorry for a wait

**Comment by phoenix-ru** [comment]
Also beware that there are breaking changes exactly regarding the URL logic. You may need to follow the release notes for that: https://auth.sidebase.io/upgrade/version-0.10.0

**Comment by agracia-foticos** [comment]
Actually, I think I have done the migration correctly, since if I disable the globalAppMiddleware I can log in and out without problems.
But when i put globalAppMiddleware to true, the first page its a 500 error (the trace of error its in this page)and automatically redirects me correctly to login page

**Comment by agracia-foticos** [comment]
i upgrade from     "@sidebase/nuxt-auth": "0.9.4",

**Comment by Invisi** [comment]
I'm able to replicate that as well on `0.10.0` and it seems to originate in the following code introduced in 578800588784f32275f3980a685987fef5ef71da: https://github.com/sidebase/nuxt-auth/blob/52d4b9a5b48431eb9d522865410d209c6d66a613/src/runtime/composables/authjs/utils/navigateToAuthPage.ts#L20-L28

In my case the `href` passed to `navigateToAuthPage` is `/api/auth/signin?callback=...`. I do have `baseURL` set to `http://localhost:3000/api/auth`[0], however `runtimeConfig.public.auth.baseURL`[1] is still `/api/auth`, resulting in the `resolveApiUrlPath("signin", runtimeConfig)` generating that invalid URL.

I disabled the `defaultProvider` during debugging, as the automatic redirect for the login didn't seem to set the state cookie correctly (#922), hence the redirect via [useAuth.signIn()](https://github.com/sidebase/nuxt-auth/blob/52d4b9a5b48431eb9d522865410d209c6d66a613/src/runtime/composables/authjs/useAuth.ts#L97).

https://github.com/sidebase/nuxt-auth/blob/52d4b9a5b48431eb9d522865410d209c6d66a613/src/runtime/utils/url.ts#L15-L26

[0] my config in `nuxt.config.ts`
```js
  auth: {
    isEnabled: true,
    disableServerSideAuth: false,
    globalAppMiddleware: true,
    originEnvKey: "AUTH_ORIGIN",
    baseURL: "http://localhost:3000/api/auth",
    provider: {
      type: "authjs",
      trustHost: false,
    },
    sessionRefresh: {
      enablePeriodically: 60 * 1000, // refresh every x seconds
      enableOnWindowFocus: true,
    },
  }
```

[1] `runtimeConfig` in `resolveApiUrlPath`
```js
"public": {
    "auth": {
        "baseURL": "/api/auth",
        "disableInternalRouting": false,
        "disableServerSideAuth": false,
        "globalAppMiddleware": true,
        "isEnabled": true,
        "originEnvKey": "AUTH_ORIGIN",
        "provider": {
            "addDefaultCallbackUrl": true,
            "defaultProvider": "",
            "trustHost": false,
            "type": "authjs"
        },
        "sessionRefresh": {
            "enableOnWindowFocus": true,
            "enablePeriodically": 60000,
            "handler": ""
        }
    }
}
```

**Comment by NathanD19** [comment]
Seeing the behavior this config.

`auth: {
    isEnabled: true,
    disableServerSideAuth: false,
    globalAppMiddleware: true,
    originEnvKey: 'http://localhost:3000',
    baseURL: 'http://localhost:3000/api/auth',

    provider: {
      type: 'authjs'           
    }
}`

**Comment by agracia-foticos** [comment]
Any advance?

**Comment by shlomi93** [comment]
Hey guys,
I've encountered this issue as well.
I was eventually able to resolve it by removing the following param in the auth block in nuxt.config.ts:
```
auth: {
        // globalAppMiddleware: true,   <------ COMMENT THIS PARAM
        isEnabled: true,
        baseURL: process.env.BASE_URL + "/api/auth/",
        sessionRefresh: {
            enablePeriodically: 1800000, // in ms
            enableOnWindowFocus: true,
        },

        provider: {
            type: "authjs",
            trustHost: false,
            addDefaultCallbackUrl: "/login",
        },
    },

 runtimeConfig: {
        authSecret: process.env.NUXT_AUTH_SECRET,
        authOrigin: process.env.BASE_URL, 
    },
```

Hope this will help you as a temporary patch for now..
BTW:
```
process.env.BASE_URL='http://localhost:3000'
```

**Comment by Plinpod** [comment]
Seeing the same issue 

config
```
auth: {
        originEnvKey: 'AUTH_ORIGIN_FULL',
        disableServerSideAuth: true,
}
```

`process.env.AUTH_ORIGIN_FULL=http://localhost:3000/api/auth`

On the page in question is have 

`
definePageMeta({
    middleware: 'sidebase-auth',
})
`

First i get the 500 Invalid URL error and then the page redirect to login path. 

If the user is logged in the page loads and then gets redirected to the login page and then redirected back to the original page.

**Comment by phoenix-ru** [comment]
Hi, can you try to [disable internal routing](https://github.com/sidebase/nuxt-auth/blob/52d4b9a5b48431eb9d522865410d209c6d66a613/src/module.ts#L29) via
```ts
auth: {
 disableInternalRouting: true 
}
```

and say if it produces a desired result? This is a new undocumented option to make `authjs` pathing behave same as `local` pathing, i.e. try to produce full URLs

**Comment by Invisi** [comment]
@phoenix-ru Setting `disableInternalRouting: true` while having `globalAppMiddleware` enabled on 0.10.0 works on my machine™ and also seems to solve #922 on my side.

**Comment by agracia-foticos** [comment]
`     disableInternalRouting : true`
not works for me... the server doesnt response in server side

**Comment by phoenix-ru** [comment]
@agracia-foticos Can you please try the fix done in #985?

```
npm i https://pkg.pr.new/@sidebase/nuxt-auth@985
```

**Comment by agracia-foticos** [comment]
> [@agracia-foticos](https://github.com/agracia-foticos) Can you please try the fix done in [#985](https://github.com/sidebase/nuxt-auth/pull/985)?
> 
> ```
> npm i https://pkg.pr.new/@sidebase/nuxt-auth@985
> ```

not works.

With disableInternalRouting : true the apps doesnt response
Without disableInternalRouting : true [@sidebase/nuxt-auth] Recursion detected at /session. Have you set the correct `auth.baseURL`?

**Comment by agracia-foticos** [comment]
> [@agracia-foticos](https://github.com/agracia-foticos) Can you please try the fix done in [#985](https://github.com/sidebase/nuxt-auth/pull/985)?
> 
> ```
> npm i https://pkg.pr.new/@sidebase/nuxt-auth@985
> ```

WORKS updating https://auth.sidebase.io/upgrade/version-0.10.0#urls-are-now-joined
And without `disableInternalRouting : true`

**Comment by phoenix-ru** [comment]
> WORKS updating https://auth.sidebase.io/upgrade/version-0.10.0#urls-are-now-joined
> And without disableInternalRouting : true

Cool, this is the desired result, URL migration is required for 0.10.0 of course.
I was able to reproduce your error `Invalid URL` on server-side and with the new version it's gone. Hopefully we can close the issue

**Comment by agracia-foticos** [comment]
> [@agracia-foticos](https://github.com/agracia-foticos) You can try using the `next` tag which includes this fix: https://www.npmjs.com/package/@sidebase/nuxt-auth/v/0.10.1-alpha.1?activeTab=versions

We are testint this version:
In local, compiling in PRO mode (npx nuxi build) and starting a server, works fine, localhost:3000 redirects to http://localhost:3000/login?callbackUrl=http://localhost:3000/ with globalAppMiddleware active

But in our staging environment with domain not works 

![Image](https://github.com/user-attachments/assets/fe2ea804-9272-4c83-9d53-60e9de027f11)

TOO MANY REDIRECTS
